name: keerthana_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  #sdk: ^3.7.2
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5 # <- Add your dependency here

    # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Encryption
  crypto: ^3.0.3
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.35.5

  geolocator: ^9.0.2
  permission_handler: ^10.4.3
  camera: ^0.10.5+2
  http: ^1.4.0
  intl: ^0.20.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  syncfusion_flutter_gauges: ^29.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Ammu.png
    - assets/girl.jpeg

