name: ammu_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  #sdk: ^3.7.2
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1 # <- Add your dependency here

    # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Encryption
  crypto: ^3.0.3
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_blue_plus: ^1.35.5

  geolocator: ^9.0.2
  camera: ^0.10.5+2
  http: ^1.4.0
  intl: ^0.20.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  syncfusion_flutter_charts: ^28.1.33
  syncfusion_flutter_gauges: ^28.1.33
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Ammu.png
    - assets/girl.jpeg
    - assets/signup.png

