// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACj3h66ESHOmVHSSCSCVTwhmoRcuJSVlA',
    appId: '1:591533067808:web:89ec94a415634c794c7645',
    messagingSenderId: '591533067808',
    projectId: 'kids-ammu-app',
    authDomain: 'kids-ammu-app.firebaseapp.com',
    storageBucket: 'kids-ammu-app.firebasestorage.app',
    measurementId: 'G-3QH5SNVYCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_pWj3FPvq44sgTpHVVPc1BwYxTDenyo',
    appId: '1:591533067808:android:ceb75f9bae0691f24c7645',
    messagingSenderId: '591533067808',
    projectId: 'kids-ammu-app',
    storageBucket: 'kids-ammu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IS8Uw0AZDK-gEHtRY4LmFnqexvtkpgI',
    appId: '1:591533067808:ios:71175414558977e94c7645',
    messagingSenderId: '591533067808',
    projectId: 'kids-ammu-app',
    storageBucket: 'kids-ammu-app.firebasestorage.app',
    iosBundleId: 'com.example.keerthanaFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1IS8Uw0AZDK-gEHtRY4LmFnqexvtkpgI',
    appId: '1:591533067808:ios:71175414558977e94c7645',
    messagingSenderId: '591533067808',
    projectId: 'kids-ammu-app',
    storageBucket: 'kids-ammu-app.firebasestorage.app',
    iosBundleId: 'com.example.keerthanaFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACj3h66ESHOmVHSSCSCVTwhmoRcuJSVlA',
    appId: '1:591533067808:web:371afcf97646fd214c7645',
    messagingSenderId: '591533067808',
    projectId: 'kids-ammu-app',
    authDomain: 'kids-ammu-app.firebaseapp.com',
    storageBucket: 'kids-ammu-app.firebasestorage.app',
    measurementId: 'G-JQPV3FRR52',
  );
}
